EmailClassifier/urls.py
from django.contrib import admin
from django.urls import path, include

import user

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("user.urls")),
    path('classifier/', include("classifier.urls")),
]

classifier/urls.py
from django.urls import path
from django.views.generic import RedirectView

from . import views

app_name = "classifier"

urlpatterns = [
    path("", views.classify_document, name="overview"),
    path("upload/", views.upload_files, name="upload_files"),
    path("results/", views.ResultHistory.as_view(), name="get_history")
]

user/urls.py
from django.urls import path
from django.views.generic import RedirectView

from . import views

app_name = "user"

urlpatterns = [
    path("", RedirectView.as_view(url="/login"), name="index"),
    path("login/", views.login_user, name="login_user"),
    path("logout/", views.logout_user, name="logout_user"),
    path("register/", views.register_user, name="register_user"),
    path("change_password/", views.change_password, name="change_password"),
    path("profile/", views.load_profile, name="load_profile"),
]

user/models.py
from django.core import validators
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField


class User(models.Model):
    username = models.CharField(unique=True, max_length=15)
    password = models.CharField(max_length=256)

    first_name = models.CharField(max_length=50)
    middle_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)

    phone_number = PhoneNumberField(null=False, blank=False)
    email = models.EmailField(unique=True, max_length=200, validators=[validators.validate_email])
    mail_address = models.CharField(max_length=750)
    occupation = models.CharField(max_length=250)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["last_name"]

user/forms.py
import re

from django import forms
from django.contrib.auth.hashers import check_password
from django.core.exceptions import ValidationError
from django.forms import ModelForm, Form

from .models import User

REG_EX = ("^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*#?&])[A-Za-z\d@$!#%*?&_-]{8,20}$")


class LoginForm(Form):
    username = forms.CharField(max_length=15)
    password = forms.CharField(max_length=256, widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].widget.attrs.update(
            {"class": "form-control", "placeholder": "username", "required": True}
        )
        self.fields["password"].widget.attrs.update(
            {"class": "form-control", "placeholder": "password", "required": True}
        )


class RegisterForm(ModelForm):
    input_password = forms.CharField(widget=forms.PasswordInput, required=True)
    confirm_password = forms.CharField(widget=forms.PasswordInput, required=True)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.fields.values():
            field.widget.attrs.update({"class": "form-control", "placeholder": field.label})

    def clean_username(self):
        username = self.cleaned_data["username"]
        if User.objects.filter(username=username).exists():
            raise ValidationError("Username already in use")
        if "_" in username:
            raise ValidationError("Username cannot contain _")
        return username

    def clean_email_address(self):
        email_address = self.cleaned_data["email"]
        if User.objects.filter(email=email_address).exists():
            raise ValidationError("Email already in use")
        return email_address

    def clean_input_password(self):
        input_password = self.cleaned_data["input_password"]
        pattern = re.compile(REG_EX)
        if re.search(pattern, input_password):
            return input_password
        else:
            raise ValidationError("Password requirements don't match")

    def clean_confirm_password(self):
        if "input_password" not in self.cleaned_data:
            return ValidationError("Password not valid")
        input_password = self.cleaned_data["input_password"]
        confirm_password = self.cleaned_data["confirm_password"]
        if input_password and confirm_password:
            if input_password != confirm_password:
                raise ValidationError("Passwords do not match")
        return confirm_password

    class Meta:
        model = User
        fields = [
            "username",
            "first_name",
            "middle_name",
            "last_name",
            "email",
            "mail_address",
            "occupation",
            "phone_number",
            "input_password",
            "confirm_password",
        ]
        exclude = ["password"]
        widgets = {"mail_address": forms.Textarea(attrs={"rows": 5})}


class ChangePasswordForm(Form):
    current_password = forms.CharField(max_length=256, widget=forms.PasswordInput)
    input_password = forms.CharField(max_length=256, widget=forms.PasswordInput)
    confirm_password = forms.CharField(max_length=256, widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.fields.values():
            field.widget.attrs.update({"class": "form-control", "placeholder": field.label})

    def clean_current_password(self):
        username = self.data.get("username", None)
        if not username:
            raise ValidationError("You must login to change passwords")

        user = User.objects.all().filter(username=username).first()
        if not user:
            raise ValidationError("Invalid user account")

        current_password = self.cleaned_data["current_password"]
        if not check_password(current_password, user.password):
            raise ValidationError("Current password doesn't match")

        return current_password

    def clean_input_password(self):
        if "current_password" not in self.cleaned_data:
            raise ValidationError("Current password doesn't match")
        input_password = self.cleaned_data["input_password"]
        pattern = re.compile(REG_EX)
        if re.search(pattern, input_password):
            return input_password
        else:
            raise ValidationError("Password requirements don't match")

    def clean_confirm_password(self):
        if "input_password" not in self.cleaned_data:
            raise ValidationError("Password not valid")
        input_password = self.cleaned_data["input_password"]
        confirm_password = self.cleaned_data["confirm_password"]
        if input_password and confirm_password:
            if input_password != confirm_password:
                raise ValidationError("Passwords do not match")
        return confirm_password

user/views.py
from django.contrib.auth.hashers import make_password, check_password
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import redirect, render

from .forms import LoginForm, RegisterForm, ChangePasswordForm
from .models import User


def login_user(request):
    if request.session.get("is_login", None):
        is_valid, user, _ = validate_n_get_user(request)
        if not is_valid:
            return redirect('user:logout_user')
        return redirect("classifier:overview")
    login_error = False
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            try:
                user = User.objects.all().filter(username=username).first()
            except ObjectDoesNotExist:
                login_error = True
            else:
                if not user or not check_password(password, user.password):
                    login_error = True
                else:
                    request.session["username"] = username
                    request.session["is_login"] = True
                    return redirect("classifier:overview")
    else:
        form = LoginForm()
    context = {"form": form, "login_error": login_error}
    return render(request, "user/login.html", context)


def register_user(request):
    if request.session.get("is_login", None):
        is_valid, user, _ = validate_n_get_user(request)
        if not is_valid:
            return redirect('user:logout_user')
        return redirect("classifier:overview")
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            password = form.cleaned_data["input_password"]
            encrypt_pwd = make_password(password)
            f = form.save(commit=False)
            f.password = encrypt_pwd
            f.save()
            return redirect("user:login_user")
    else:
        form = RegisterForm()
    context = {
        "form": form
    }
    return render(request, "user/register.html", context)


def change_password(request):
    is_valid, user, context = validate_n_get_user(request)
    if not is_valid:
        return redirect('user:logout_user')
    match_error = False
    if request.method == "POST":
        form = ChangePasswordForm(request.POST)
        if form.is_valid():
            new_password = form.cleaned_data["input_password"]
            old_password = form.cleaned_data["current_password"]
            username = request.session.get("username", None)
            encrypt_pwd = make_password(new_password)
            try:
                user = User.objects.all().filter(username=username).first()
            except ObjectDoesNotExist:
                return redirect("user:logout_user")
            else:
                if check_password(old_password, user.password):
                    user.password = encrypt_pwd
                    user.save()
                    # Todo - add a popup
                    return redirect("classifier:overview")
                else:
                    match_error = True
    else:
        form = ChangePasswordForm()
    context.update({
        "form": form,
        "match_error": match_error
    })
    return render(request, "user/change_password.html", context)


def logout_user(request):
    request.session.flush()
    return redirect("user:login_user")


def load_profile(request):
    is_valid, user, context = validate_n_get_user(request)
    if not is_valid:
        return redirect('user:logout_user')
    profile_info = [
        {"label": "Username",
         "value": user.username
         },
        {"label": "Email",
         "value": user.email
         },
        {"label": "Name (First, Middle, Last)",
         "value": f"{user.first_name} {user.middle_name} {user.last_name}"
         },
        {"label": "Phone_number",
         "value": user.phone_number
         },
        {"label": "Mail_address",
         "value": user.mail_address
         },
        {"label": "Occupation",
         "value": user.occupation
         },
    ]
    context["profile"] = profile_info
    return render(request, "user/profile.html", context)


def get_user(request):
    is_login = request.session.get("is_login", None)
    if not is_login:
        return None, None
    username = request.session.get("username", None)
    user = None
    context = {"unauth": True}
    if username:
        try:
            user = User.objects.get(username=username)
            context["unauth"] = False
        except ObjectDoesNotExist:
            context["unauth"] = True
        else:
            context["user"] = {
                "username": user.username,
                "fname": user.first_name,
                "lname": user.last_name,
                "abv_name": f"{user.first_name} {user.middle_name[0].upper()}. {user.last_name}",
            }
    return user, context


def validate_n_get_user(request=None):
    if not request:
        return False, None, None
    is_valid = False
    user, context = get_user(request)
    if user:
        is_valid = True
    return is_valid, user, context

user/templates/user/change_password.html
{% extends "base/base.html" %}
{% block content %}
    <div class="container-fluid">
        <div class="row"
             style="display: flex; flex-direction: row; justify-content: center; padding: 2.5% 2.5% 1% 2.5%">
            <div class="col-md-6">
                <form action="{% url 'user:change_password' %}" method="post"
                      style="padding-top: 70px;">
                    {% csrf_token %}
                    <input type="hidden" name="username" value="{{ user.username }}">
                    <div class="text-center mb-4">
                        <h1 class="h3 mb-3 font-weight-normal">Let's change your password...</h1>
                        <h4 class="h5 mb-5 font-weight-light">to continue, we'll require your</h4>
                    </div>
                    <div class="form-row">
                        <div class="form-label-group col-md-6">
                            {{ form.current_password }}
                            <label for={{ form.current_password.id_for_label }}>{{ form.current_password.label }}</label>
                            {% for error in form.current_password.errors %}
                                <p class="help-block text-danger mt-2">{{ error }}</p>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="mt-2" style="font-size: 15px;">
                        Password should contain at least-
                        <div class="form-row">
                            <div class="col-md-6">
                                <ul>
                                    <li>8 characters</li>
                                    <li>1 Lowercase character</li>
                                    <li>1 special character [@#$%^&+=_-]</li>
                                </ul>
                            </div>
                            <div class="col-md-6">
                                <ul>
                                    <li>1 Uppercase character</li>
                                    <li>1 digit</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-label-group col-md-6">
                            {{ form.input_password }}
                            <label for={{ form.input_password.id_for_label }}>{{ form.input_password.label }}</label>
                            {% for error in form.input_password.errors %}
                                <p class="help-block text-danger mt-2">{{ error }}</p>
                            {% endfor %}
                        </div>
                        <div class="form-label-group col-md-6">
                            {{ form.confirm_password }}
                            <label for={{ form.confirm_password.id_for_label }}>{{ form.confirm_password.label }}</label>
                            {% for error in form.confirm_password.errors %}
                                <p class="help-block text-danger mt-2">{{ error }}</p>
                            {% endfor %}
                        </div>
                    </div>

                    <div style="display: flex; flex-flow: row wrap; justify-content: center">
                        <a href="{% url 'classifier:overview' %}"
                           class="btn btn-outline-info mt-3 mr-3">Back
                        </a>
                        <input class="btn btn-primary mt-3 ml-3" type="submit"
                               value="Update Password"/>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

user/templates/user/login.html
{% extends "base/base.html" %}
{% block content %}
    <div class="login-div"
         style="display: flex; flex-direction: row; justify-content: center; padding: 2.5% 2.5% 1% 2.5%">
        <div style="width:40%; padding: 5%;">
            <form action="{% url 'user:login_user' %}" method="post" class="form-signin">
                {% csrf_token %}
                <div class="text-center mb-4">
                    <h1 class="h3 mb-3 font-weight-normal">Hello again...</h1>
                    <h4 class="h5 mb-3 font-weight-light">to continue, login with your</h4>
                </div>
                {% for field in form %}
                    <div class="form-label-group">
                        {{ field }}
                        <label for={{ field.id_for_label }}>{{ field.label }}</label>
                    </div>
                {% endfor %}
                {% if login_error %}
                    <p class="errorlist" style="color: red">Invalid credentials</p>
                {% endif %}
                <button type="submit" class="btn btn-lg btn-primary btn-block">
                    <span class="spinner-border spinner-border-sm display_none" role="status"
                          aria-hidden="true"></span>
                    Login
                </button>
            </form>
        </div>
    </div>
    <div class="register-popup-div" style="font-size: 16px;display: flex;flex-direction: row;justify-content: center;padding: 1% 2.5% 2.5% 2.5%">
        <span>Don't have an account, yet?</span>
        <a href="{% url 'user:register_user' %}">Sign Up!</a>
    </div>
{% endblock %}

user/templates/user/profile.html
{% extends "base/base.html" %}
{% block content %}
    <h5>Your information that is saved with us</h5>

    <div class="container-fluid">
        <div class="row" style="font-size: 16px; display: flex;flex-direction: row;padding: 1%">
            <div class="col-md-6">
                {% for section in profile %}
                    <div class="mb-5">
                        <h6>{{ section.label }}</h6>
                        <p>{{ section.value }}</p>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>


{% endblock %}

user/templates/user/register.html
{% extends "base/base.html" %}
{% block content %}
    <div class="container-fluid">
        <div class="row"
             style="display: flex;flex-direction: row;justify-content: center;padding: 1% 2.5% 2.5% 2.5%">
            <div class="col-md-6">
                <form action="{% url 'user:register_user' %}" method="post" class="form-signup"
                      style="padding-top: 70px;">
                    {% csrf_token %}
                    <div class="text-center mb-4">
                        <h1 class="h3 mb-3 font-weight-normal">Let's get you started...</h1>
                        <h4 class="h5 mb-3 font-weight-light">to continue, we'll require your</h4>
                    </div>

                    <div class="form-row">
                        <div class="form-label-group col-md-4">
                            {{ form.first_name }}
                            <label for={{ form.first_name.id_for_label }}>{{ form.first_name.label }}</label>
                            {% for error in form.first_name.errors %}
                                <p class="help-block text-danger mt-2">{{ error }}</p>
                            {% endfor %}
                        </div>
                        <div class="form-label-group col-md-4">
                            {{ form.middle_name }}
                            <label for={{ form.middle_name.id_for_label }}>{{ form.middle_name.label }}</label>
                            {% for error in form.middle_name.errors %}
                                <p class="help-block text-danger mt-2">{{ error }}</p>
                            {% endfor %}
                        </div>
                        <div class="form-label-group col-md-4">
                            {{ form.last_name }}
                            <label for={{ form.last_name.id_for_label }}>{{ form.last_name.label }}</label>
                            {% for error in form.last_name.errors %}
                                <p class="help-block text-danger mt-2">{{ error }}</p>
                            {% endfor %}
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="form-label-group col-md-6">
                            {{ form.phone_number }}
                            <label for={{ form.phone_number.id_for_label }}>{{ form.phone_number.label }}</label>

                            {% for error in form.phone_number.errors %}
                                <p class="help-block text-danger mt-2">{{ error }}</p>
                            {% endfor %}
                        </div>
                        <div class="form-label-group col-md-6">
                            {{ form.occupation }}
                            <label for={{ form.occupation.id_for_label }}>{{ form.occupation.label }}</label>
                            {% for error in form.occupation.errors %}
                                <p class="help-block text-danger mt-2">{{ error }}</p>
                            {% endfor %}
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="form-label-group col-md-12">
                            {{ form.mail_address }}
                            <label for={{ form.mail_address.id_for_label }}>{{ form.mail_address.label }}</label>

                            {% for error in form.mail_address.errors %}
                                <p class="help-block text-danger mt-2">{{ error }}</p>
                            {% endfor %}
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="form-label-group col-md-6">
                            {{ form.username }}
                            <label for={{ form.username.id_for_label }}>{{ form.username.label }}</label>

                            {% for error in form.username.errors %}
                                <p class="help-block text-danger mt-2">{{ error }}</p>
                            {% endfor %}
                        </div>
                        <div class="form-label-group col-md-6">
                            {{ form.email }}
                            <label for={{ form.email.id_for_label }}>{{ form.email.label }}</label>
                            {% for error in form.email.errors %}
                                <p class="help-block text-danger mt-2">{{ error }}</p>
                            {% endfor %}
                        </div>
                    </div>

                    <div class="mt-2" style="font-size: 15px;">
                        Password should contain at least-
                        <div class="form-row">
                            <div class="col-md-6">
                                <ul>
                                    <li>8 characters</li>
                                    <li>1 Lowercase character</li>
                                    <li>1 special character [@#$%^&+=_-]</li>
                                </ul>
                            </div>
                            <div class="col-md-6">
                                <ul>
                                    <li>1 Uppercase character</li>
                                    <li>1 digit</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-label-group col-md-6">
                            {{ form.input_password }}
                            <label for={{ form.input_password.id_for_label }}>{{ form.input_password.label }}</label>
                            {% for error in form.input_password.errors %}
                                <p class="help-block text-danger mt-2">{{ error }}</p>
                            {% endfor %}
                        </div>
                        <div class="form-label-group col-md-6">
                            {{ form.confirm_password }}
                            <label for={{ form.confirm_password.id_for_label }}>{{ form.confirm_password.label }}</label>
                            {% for error in form.confirm_password.errors %}
                                <p class="help-block text-danger mt-2">{{ error }}</p>
                            {% endfor %}
                        </div>
                    </div>
                    <input class="btn btn-lg btn-primary btn-block" type="submit" value="Register"/>
                </form>
            </div>
        </div>

        <div class="login-popup-div"
             style="font-size: 16px;display: flex;flex-direction: row;justify-content: center;padding: 1% 2.5% 2.5% 2.5%">
            <span>Already have an account?</span>
            <a href="{% url 'user:login_user' %}">Sign In!</a>
        </div>
    </div>
    <script>
        $(document).ready(function () {
            $(".form-control").each(function () {
                $(this).prop("autocomplete", "off");
            })
        })
    </script>
{% endblock %}