EmailClassifier/urls.py
from django.contrib import admin
from django.urls import path, include

import user

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("user.urls")),
    path('classifier/', include("classifier.urls")),
]

classifier/urls.py
from django.urls import path
from django.views.generic import RedirectView

from . import views

app_name = "classifier"

urlpatterns = [
    path("", views.classify_document, name="overview"),
    path("upload/", views.upload_files, name="upload_files"),
    path("results/", views.ResultHistory.as_view(), name="get_history")
]

user/urls.py
from django.urls import path
from django.views.generic import RedirectView

from . import views

app_name = "user"

urlpatterns = [
    path("", RedirectView.as_view(url="/login"), name="index"),
    path("login/", views.login_user, name="login_user"),
    path("logout/", views.logout_user, name="logout_user"),
    path("register/", views.register_user, name="register_user"),
    path("change_password/", views.change_password, name="change_password"),
    path("profile/", views.load_profile, name="load_profile"),
]

base/models.py
from django.db import models

# Create your models here.

base/views.py
from rest_framework.response import Response


def load_confirm_modal(action_url, title="Confirm", body=""):
    context = {
        "action_url": action_url,
        "modal_title": title,
        "modal_body": body if body else "",
    }
    return Response(context, template_name="base/confirm_modal.html")


def load_success_modal(success_msg, extra_msgs=None):
    context = {"success_message": success_msg, "messages": extra_msgs}
    return Response(context, template_name="base/success_modal.html")


def load_error_modal(error_message, errors=None):
    context = {"error_message": error_message, "errors": errors}
    return Response(context, template_name="base/error_modal.html")

base/templates/base/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <script src="{% static 'base/js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'base/js/popper.min.js' %}"></script>
    <script src="{% static 'base/js/moment.min.js' %}"></script>
    <script src="{% static 'base/js/bootstrap.min.js' %}"></script>
    <script src="https://kit.fontawesome.com/fc24e2383c.js" crossorigin="anonymous"></script>

    <link type="text/css" href="{% static 'base/css/bootstrap.min.css' %}" rel="stylesheet">
    <link type="text/css" href="{% static 'base/css/base.css' %}" rel="stylesheet">
    <title>{% block title %}Email Classifier{% endblock %}</title>
</head>
<body>
{% block navbar %}
    {% include 'base/navbar.html' %}
{% endblock %}
<div class="base-content">
    {% block content %}{% endblock %}
</div>
{% block modals %}
    <div class="modal fade" tabindex="-1" role="dialog" id="base_modal" data-backdrop="static">
        {% include 'base/base_modal.html' %}
    </div>
{% endblock %}
</body>

<script type="text/javascript">
    $(document).ready(function () {
        $("#base_modal").on('show.bs.modal', function (e) {
            console.log("show");
            if (e.relatedTarget !== undefined) {
                $(e.relatedTarget).prop("disabled", false);
                $(e.relatedTarget).children(".spinner-border").addClass("display_none");
            }
        });
        $("#base_modal").on('hidden.bs.modal', function (e) {
            window.location.reload();
        });
        $(".btn").on("click", function (e) {
            if ($(this).prop("type") === "submit") {
                return true;
            }
            $(this).prop("disabled", true);
            $(this).children(".spinner-border").removeClass("display_none");
            return true;
        });
        $(document).on("submit", "form", function (e) {
            $(e.originalEvent.submitter).prop("disabled", true);
            $(e.originalEvent.submitter).children(".spinner-border").removeClass("display_none");
        });
    });

</script>
</html>

base/templates/base/base_modal.html
<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">{{ modal_title|default:"Action" }}</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% block modal_content %}
        {% endblock %}
    </div>
</div>

base/templates/base/confirm_modal.html
<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">{{ modal_title|default:"Confirm" }}</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            {% if modal_body %}
                {{ modal_body|safe }}
            {% else %}
                <h6>Are you sure you want to proceed with this operation?</h6>
                <span>Please click <b>Confirm</b> to proceed or <b>Close</b> to go back.</span>
            {% endif %}
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary modal-success-btn confirm-btn">
                <span class="spinner-border spinner-border-sm display_none" role="status" aria-hidden="true" ></span>
                Confirm
            </button>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $(".confirm-btn").on("click", function () {
            let this_btn = $(this);
            this_btn.prop("disabled", true);
            this_btn.children(".spinner-border").removeClass("display_none");
            $.ajax({
                type: "POST",
                url: "{{ action_url }}",
                contentType: "application/json",
                processData: false,
                data: JSON.stringify({"confirm": 1}),
                success: function (response) {
                    $("#base_modal").html(response);
                    this_btn.prop("disabled", false);
                    this_btn.children(".spinner-border").addClass("display_none");
                }
            });
            return false;
        })
    })
</script>

base/templates/base/error_modal.html
<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">{{ modal_title|default:"Error" }}</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            {% if error_message %}
                <span>{{ error_message|safe }}</span>
            {% else %}
                <span>Error occurred while processing your request.</span>
            {% endif %}<br><br>
            {% for error in errors %}
                <span><b>Error Code</b> - {{ error.code|safe }}<br></span>
                <p><b>Error Message</b> - {{ error.message|linebreaksbr }}</p>
            {% endfor %}
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-primary modal-success-btn" data-dismiss="modal">
                Close
            </button>
        </div>
    </div>
</div>

base/templates/base/navbar.html
{% block top_navbar %}
    <nav class="top-nav navbar navbar-expand-md" style="background-color: white">
        <div class="brand-controls">
            <a class="text-dark" href="/" style="text-decoration: none;width:50%;">
                <h3>SS Email Classifier</h3>
            </a>
            {% if user and "abv_name" in user %}
                <div class="user-info-div">
                    <h6 class="mr-3 mb-0">Welcome, {{ user.abv_name }}!</h6>
                    <div class="dropdown settings-con">
                    <span id="dropdownMenu" data-toggle="dropdown" aria-haspopup="true"
                          aria-expanded="false" style="cursor: pointer; font-size: 16px;">
                        <i class="fa fa-gear"></i></span>
                        <div class="dropdown-menu dropdown-menu-sm-right"
                             aria-labelledby="dropdown">
                            <a class="dropdown-item" href="{% url 'user:change_password' %}">
                                Change Password</a>
                            <a class="dropdown-item" href="{% url 'user:logout_user' %}">Logout</a>
                        </div>
                    </div>
                </div>
            {% endif %}
        </div>
        {% if user and "abv_name" in user %}
            <div class="navbar-con">
                <ul class="nav nav-tabs">
                    <li class="nav-item">
                        <a class="nav-link {% if "classifier" in request.get_full_path and "results" not in request.get_full_path %} active {% endif %}"
                           href="{% url 'classifier:overview' %}">Dashboard</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if "results" in request.get_full_path %} active {% endif %}"
                           href="{% url 'classifier:get_history' %}">Results</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if "profile" in request.get_full_path %} active {% endif %}"
                           href="{% url 'user:load_profile' %}">Profile</a>
                    </li>
                </ul>
            </div>
        {% endif %}
    </nav>
{% endblock %}

base/templates/base/success_modal.html
<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">{{ modal_title|default:"Success" }}</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            {% if success_message %}
                <span>{{ success_message|safe }}</span>
            {% else %}
                <span>The instructions executed successfully</span>
            {% endif %}
            {% if messages %}
                {% for msg in messages %}
                    <span>{{ msg.title }}</span>
                    <span>{{ msg.message }}</span>
                {% endfor %}
            {% endif %}
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-primary modal-success-btn" data-dismiss="modal">
                Okay
            </button>
        </div>
    </div>
</div>